# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/watches/code/GUFG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/watches/code/GUFG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/watches/code/GUFG/CMakeFiles /home/watches/code/GUFG/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/watches/code/GUFG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named keytest

# Build rule for target.
keytest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keytest
.PHONY : keytest

# fast build rule for target.
keytest/fast:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/build
.PHONY : keytest/fast

aux.o: aux.cc.o
.PHONY : aux.o

# target to build an object file
aux.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/aux.cc.o
.PHONY : aux.cc.o

aux.i: aux.cc.i
.PHONY : aux.i

# target to preprocess a source file
aux.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/aux.cc.i
.PHONY : aux.cc.i

aux.s: aux.cc.s
.PHONY : aux.s

# target to generate assembly for a file
aux.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/aux.cc.s
.PHONY : aux.cc.s

character.o: character.cc.o
.PHONY : character.o

# target to build an object file
character.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/character.cc.o
.PHONY : character.cc.o

character.i: character.cc.i
.PHONY : character.i

# target to preprocess a source file
character.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/character.cc.i
.PHONY : character.cc.i

character.s: character.cc.s
.PHONY : character.s

# target to generate assembly for a file
character.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/character.cc.s
.PHONY : character.cc.s

draw.o: draw.cc.o
.PHONY : draw.o

# target to build an object file
draw.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/draw.cc.o
.PHONY : draw.cc.o

draw.i: draw.cc.i
.PHONY : draw.i

# target to preprocess a source file
draw.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/draw.cc.i
.PHONY : draw.cc.i

draw.s: draw.cc.s
.PHONY : draw.s

# target to generate assembly for a file
draw.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/draw.cc.s
.PHONY : draw.cc.s

hitstun.o: hitstun.cc.o
.PHONY : hitstun.o

# target to build an object file
hitstun.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/hitstun.cc.o
.PHONY : hitstun.cc.o

hitstun.i: hitstun.cc.i
.PHONY : hitstun.i

# target to preprocess a source file
hitstun.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/hitstun.cc.i
.PHONY : hitstun.cc.i

hitstun.s: hitstun.cc.s
.PHONY : hitstun.s

# target to generate assembly for a file
hitstun.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/hitstun.cc.s
.PHONY : hitstun.cc.s

interface.o: interface.cc.o
.PHONY : interface.o

# target to build an object file
interface.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/interface.cc.o
.PHONY : interface.cc.o

interface.i: interface.cc.i
.PHONY : interface.i

# target to preprocess a source file
interface.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/interface.cc.i
.PHONY : interface.cc.i

interface.s: interface.cc.s
.PHONY : interface.s

# target to generate assembly for a file
interface.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/interface.cc.s
.PHONY : interface.cc.s

keytest.o: keytest.cc.o
.PHONY : keytest.o

# target to build an object file
keytest.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/keytest.cc.o
.PHONY : keytest.cc.o

keytest.i: keytest.cc.i
.PHONY : keytest.i

# target to preprocess a source file
keytest.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/keytest.cc.i
.PHONY : keytest.cc.i

keytest.s: keytest.cc.s
.PHONY : keytest.s

# target to generate assembly for a file
keytest.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/keytest.cc.s
.PHONY : keytest.cc.s

move.o: move.cc.o
.PHONY : move.o

# target to build an object file
move.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/move.cc.o
.PHONY : move.cc.o

move.i: move.cc.i
.PHONY : move.i

# target to preprocess a source file
move.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/move.cc.i
.PHONY : move.cc.i

move.s: move.cc.s
.PHONY : move.s

# target to generate assembly for a file
move.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/move.cc.s
.PHONY : move.cc.s

player.o: player.cc.o
.PHONY : player.o

# target to build an object file
player.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/player.cc.o
.PHONY : player.cc.o

player.i: player.cc.i
.PHONY : player.i

# target to preprocess a source file
player.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/player.cc.i
.PHONY : player.cc.i

player.s: player.cc.s
.PHONY : player.s

# target to generate assembly for a file
player.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/player.cc.s
.PHONY : player.cc.s

red.o: red.cc.o
.PHONY : red.o

# target to build an object file
red.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/red.cc.o
.PHONY : red.cc.o

red.i: red.cc.i
.PHONY : red.i

# target to preprocess a source file
red.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/red.cc.i
.PHONY : red.cc.i

red.s: red.cc.s
.PHONY : red.s

# target to generate assembly for a file
red.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/red.cc.s
.PHONY : red.cc.s

special.o: special.cc.o
.PHONY : special.o

# target to build an object file
special.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/special.cc.o
.PHONY : special.cc.o

special.i: special.cc.i
.PHONY : special.i

# target to preprocess a source file
special.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/special.cc.i
.PHONY : special.cc.i

special.s: special.cc.s
.PHONY : special.s

# target to generate assembly for a file
special.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/special.cc.s
.PHONY : special.cc.s

trie.o: trie.cc.o
.PHONY : trie.o

# target to build an object file
trie.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/trie.cc.o
.PHONY : trie.cc.o

trie.i: trie.cc.i
.PHONY : trie.i

# target to preprocess a source file
trie.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/trie.cc.i
.PHONY : trie.cc.i

trie.s: trie.cc.s
.PHONY : trie.s

# target to generate assembly for a file
trie.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/trie.cc.s
.PHONY : trie.cc.s

utility.o: utility.cc.o
.PHONY : utility.o

# target to build an object file
utility.cc.o:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/utility.cc.o
.PHONY : utility.cc.o

utility.i: utility.cc.i
.PHONY : utility.i

# target to preprocess a source file
utility.cc.i:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/utility.cc.i
.PHONY : utility.cc.i

utility.s: utility.cc.s
.PHONY : utility.s

# target to generate assembly for a file
utility.cc.s:
	$(MAKE) -f CMakeFiles/keytest.dir/build.make CMakeFiles/keytest.dir/utility.cc.s
.PHONY : utility.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... keytest"
	@echo "... rebuild_cache"
	@echo "... aux.o"
	@echo "... aux.i"
	@echo "... aux.s"
	@echo "... character.o"
	@echo "... character.i"
	@echo "... character.s"
	@echo "... draw.o"
	@echo "... draw.i"
	@echo "... draw.s"
	@echo "... hitstun.o"
	@echo "... hitstun.i"
	@echo "... hitstun.s"
	@echo "... interface.o"
	@echo "... interface.i"
	@echo "... interface.s"
	@echo "... keytest.o"
	@echo "... keytest.i"
	@echo "... keytest.s"
	@echo "... move.o"
	@echo "... move.i"
	@echo "... move.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... red.o"
	@echo "... red.i"
	@echo "... red.s"
	@echo "... special.o"
	@echo "... special.i"
	@echo "... special.s"
	@echo "... trie.o"
	@echo "... trie.i"
	@echo "... trie.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

